### ISSUE TITLE
Configuring the log level

### ISSUE THREAD

**Issue by jamesrichard91** [blackducksoftware/hub-teamcity#1]
The log level should be configurable. The level should be configurable through an environment variable (HUB_LOG_LEVEL) , and when the Build runs we should only be logging messages of that level and below. Default : INFO
Ex :
WARN chosen :
log ERROR and WARN
DEBUG chosen:
log ERROR, WARN, INFO, and DEBUG

**Comment by utsavsanghani** [comment]
Fixed in 1.4.1
